name: build dylan-nbody-app

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

env:
  DYLAN: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v3
        with:
          path: |
            ./_packages
            ./registry
          key: ${{ runner.os }}-${{ hashFiles('**/dylan-package.json') }}

      - name: Install Opendylan
        uses: dylan-lang/install-opendylan@v3
        with:
          version: 2023.1
          tag: v2023.1.0

      - name: Download dependencies
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: dylan update

      - name: Build dylan-nbody-app
        run: dylan build dylan-nbody-app

      - name: Upload application artifact
        uses: actions/upload-artifact@v3
        with:
          name: dylan-nbody-app
          path: |
            /home/runner/work/dylan-nbody/dylan-nbody/_build/bin
            /home/runner/work/dylan-nbody/dylan-nbody/_build/lib



