name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: Install Opendylan
        uses: dylan-lang/install-opendylan@v3
        with:
          version: 2023.1
          tag: v2023.1.0

      - name: Download dependencies
        run: dylan update
        
      - name: Build tests
        run: dylan build dylan-nbody-test-suite

      - name: Run tests
        run: _build/bin/dylan-nbody-test-suite

